package com.pantuo.mybatis.persistence;

import com.pantuo.mybatis.domain.Supplies;
import com.pantuo.mybatis.domain.SuppliesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SuppliesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    int countByExample(SuppliesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    int deleteByExample(SuppliesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    int insert(Supplies record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    int insertSelective(Supplies record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    List<Supplies> selectByExample(SuppliesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    Supplies selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Supplies record, @Param("example") SuppliesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Supplies record, @Param("example") SuppliesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Supplies record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Supplies record);
}