package com.pantuo.mybatis.persistence;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.pantuo.mybatis.domain.SuppliesHistory;
import com.pantuo.mybatis.domain.SuppliesHistoryExample;

public interface SuppliesHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    int countByExample(SuppliesHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    int deleteByExample(SuppliesHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    int insert(SuppliesHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    int insertSelective(SuppliesHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    List<SuppliesHistory> selectByExample(SuppliesHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    SuppliesHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SuppliesHistory record, @Param("example") SuppliesHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SuppliesHistory record, @Param("example") SuppliesHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SuppliesHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SuppliesHistory record);
}