package com.pantuo.mybatis.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SuppliesHistoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    protected int limitEnd = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    protected String defaultVisible = "1";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    protected String defaultStatusNot = "del";

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    public SuppliesHistoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    public void setDefaultVisible(String defaultVisible) {
        this.defaultVisible=defaultVisible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    public String getDefaultVisible() {
        return defaultVisible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    public void setDefaultStatusNot(String defaultStatusNot) {
        this.defaultStatusNot=defaultStatusNot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    public String getDefaultStatusNot() {
        return defaultStatusNot;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    protected abstract class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition.startsWith("visible")) {
                SuppliesHistoryExample.this.defaultVisible = null;
            }
            if (condition.startsWith("status")) {
                SuppliesHistoryExample.this.defaultStatusNot = null;
            }
            if (condition == null) {
                return ;
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (condition.startsWith("visible")) {
                SuppliesHistoryExample.this.defaultVisible = null;
            }
            if (condition.startsWith("status")) {
                SuppliesHistoryExample.this.defaultStatusNot = null;
            }
            if (value == null) {
                return ;
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (condition.startsWith("visible")) {
                SuppliesHistoryExample.this.defaultVisible = null;
            }
            if (condition.startsWith("status")) {
                SuppliesHistoryExample.this.defaultStatusNot = null;
            }
            if (value1 == null || value2 == null) {
                return ;
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSuppliesIdIsNull() {
            addCriterion("supplies_id is null");
            return (Criteria) this;
        }

        public Criteria andSuppliesIdIsNotNull() {
            addCriterion("supplies_id is not null");
            return (Criteria) this;
        }

        public Criteria andSuppliesIdEqualTo(Integer value) {
            addCriterion("supplies_id =", value, "suppliesId");
            return (Criteria) this;
        }

        public Criteria andSuppliesIdNotEqualTo(Integer value) {
            addCriterion("supplies_id <>", value, "suppliesId");
            return (Criteria) this;
        }

        public Criteria andSuppliesIdGreaterThan(Integer value) {
            addCriterion("supplies_id >", value, "suppliesId");
            return (Criteria) this;
        }

        public Criteria andSuppliesIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("supplies_id >=", value, "suppliesId");
            return (Criteria) this;
        }

        public Criteria andSuppliesIdLessThan(Integer value) {
            addCriterion("supplies_id <", value, "suppliesId");
            return (Criteria) this;
        }

        public Criteria andSuppliesIdLessThanOrEqualTo(Integer value) {
            addCriterion("supplies_id <=", value, "suppliesId");
            return (Criteria) this;
        }

        public Criteria andSuppliesIdIn(List<Integer> values) {
            addCriterion("supplies_id in", values, "suppliesId");
            return (Criteria) this;
        }

        public Criteria andSuppliesIdNotIn(List<Integer> values) {
            addCriterion("supplies_id not in", values, "suppliesId");
            return (Criteria) this;
        }

        public Criteria andSuppliesIdBetween(Integer value1, Integer value2) {
            addCriterion("supplies_id between", value1, value2, "suppliesId");
            return (Criteria) this;
        }

        public Criteria andSuppliesIdNotBetween(Integer value1, Integer value2) {
            addCriterion("supplies_id not between", value1, value2, "suppliesId");
            return (Criteria) this;
        }

        public Criteria andStatsIsNull() {
            addCriterion("stats is null");
            return (Criteria) this;
        }

        public Criteria andStatsIsNotNull() {
            addCriterion("stats is not null");
            return (Criteria) this;
        }

        public Criteria andStatsEqualTo(String value) {
            addCriterion("stats =", value, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsNotEqualTo(String value) {
            addCriterion("stats <>", value, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsGreaterThan(String value) {
            addCriterion("stats >", value, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsGreaterThanOrEqualTo(String value) {
            addCriterion("stats >=", value, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsLessThan(String value) {
            addCriterion("stats <", value, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsLessThanOrEqualTo(String value) {
            addCriterion("stats <=", value, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsLike(String value) {
            addCriterion("stats like", value, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsNotLike(String value) {
            addCriterion("stats not like", value, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsIn(List<String> values) {
            addCriterion("stats in", values, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsNotIn(List<String> values) {
            addCriterion("stats not in", values, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsBetween(String value1, String value2) {
            addCriterion("stats between", value1, value2, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsNotBetween(String value1, String value2) {
            addCriterion("stats not between", value1, value2, "stats");
            return (Criteria) this;
        }

        public Criteria andOperUserIsNull() {
            addCriterion("oper_user is null");
            return (Criteria) this;
        }

        public Criteria andOperUserIsNotNull() {
            addCriterion("oper_user is not null");
            return (Criteria) this;
        }

        public Criteria andOperUserEqualTo(String value) {
            addCriterion("oper_user =", value, "operUser");
            return (Criteria) this;
        }

        public Criteria andOperUserNotEqualTo(String value) {
            addCriterion("oper_user <>", value, "operUser");
            return (Criteria) this;
        }

        public Criteria andOperUserGreaterThan(String value) {
            addCriterion("oper_user >", value, "operUser");
            return (Criteria) this;
        }

        public Criteria andOperUserGreaterThanOrEqualTo(String value) {
            addCriterion("oper_user >=", value, "operUser");
            return (Criteria) this;
        }

        public Criteria andOperUserLessThan(String value) {
            addCriterion("oper_user <", value, "operUser");
            return (Criteria) this;
        }

        public Criteria andOperUserLessThanOrEqualTo(String value) {
            addCriterion("oper_user <=", value, "operUser");
            return (Criteria) this;
        }

        public Criteria andOperUserLike(String value) {
            addCriterion("oper_user like", value, "operUser");
            return (Criteria) this;
        }

        public Criteria andOperUserNotLike(String value) {
            addCriterion("oper_user not like", value, "operUser");
            return (Criteria) this;
        }

        public Criteria andOperUserIn(List<String> values) {
            addCriterion("oper_user in", values, "operUser");
            return (Criteria) this;
        }

        public Criteria andOperUserNotIn(List<String> values) {
            addCriterion("oper_user not in", values, "operUser");
            return (Criteria) this;
        }

        public Criteria andOperUserBetween(String value1, String value2) {
            addCriterion("oper_user between", value1, value2, "operUser");
            return (Criteria) this;
        }

        public Criteria andOperUserNotBetween(String value1, String value2) {
            addCriterion("oper_user not between", value1, value2, "operUser");
            return (Criteria) this;
        }

        public Criteria andOperCommentIsNull() {
            addCriterion("oper_comment is null");
            return (Criteria) this;
        }

        public Criteria andOperCommentIsNotNull() {
            addCriterion("oper_comment is not null");
            return (Criteria) this;
        }

        public Criteria andOperCommentEqualTo(String value) {
            addCriterion("oper_comment =", value, "operComment");
            return (Criteria) this;
        }

        public Criteria andOperCommentNotEqualTo(String value) {
            addCriterion("oper_comment <>", value, "operComment");
            return (Criteria) this;
        }

        public Criteria andOperCommentGreaterThan(String value) {
            addCriterion("oper_comment >", value, "operComment");
            return (Criteria) this;
        }

        public Criteria andOperCommentGreaterThanOrEqualTo(String value) {
            addCriterion("oper_comment >=", value, "operComment");
            return (Criteria) this;
        }

        public Criteria andOperCommentLessThan(String value) {
            addCriterion("oper_comment <", value, "operComment");
            return (Criteria) this;
        }

        public Criteria andOperCommentLessThanOrEqualTo(String value) {
            addCriterion("oper_comment <=", value, "operComment");
            return (Criteria) this;
        }

        public Criteria andOperCommentLike(String value) {
            addCriterion("oper_comment like", value, "operComment");
            return (Criteria) this;
        }

        public Criteria andOperCommentNotLike(String value) {
            addCriterion("oper_comment not like", value, "operComment");
            return (Criteria) this;
        }

        public Criteria andOperCommentIn(List<String> values) {
            addCriterion("oper_comment in", values, "operComment");
            return (Criteria) this;
        }

        public Criteria andOperCommentNotIn(List<String> values) {
            addCriterion("oper_comment not in", values, "operComment");
            return (Criteria) this;
        }

        public Criteria andOperCommentBetween(String value1, String value2) {
            addCriterion("oper_comment between", value1, value2, "operComment");
            return (Criteria) this;
        }

        public Criteria andOperCommentNotBetween(String value1, String value2) {
            addCriterion("oper_comment not between", value1, value2, "operComment");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table supplies_history
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}