package com.pantuo.mybatis.domain;

import java.io.Serializable;
import java.util.Date;

public class Supplies implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplies.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplies.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplies.supplies_type
     *
     * @mbggenerated
     */
    private String suppliesType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplies.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplies.file_path
     *
     * @mbggenerated
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplies.info_context
     *
     * @mbggenerated
     */
    private String infoContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplies.stats
     *
     * @mbggenerated
     */
    private String stats;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplies.oper_fristuser
     *
     * @mbggenerated
     */
    private String operFristuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplies.oper_fristcomment
     *
     * @mbggenerated
     */
    private String operFristcomment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplies.oper_finaluser
     *
     * @mbggenerated
     */
    private String operFinaluser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplies.oper_finalcomment
     *
     * @mbggenerated
     */
    private String operFinalcomment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplies.seq_number
     *
     * @mbggenerated
     */
    private String seqNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplies.car_numer
     *
     * @mbggenerated
     */
    private String carNumer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplies.response_cid
     *
     * @mbggenerated
     */
    private String responseCid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplies.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplies.edit_time
     *
     * @mbggenerated
     */
    private Date editTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplies
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplies.id
     *
     * @return the value of supplies.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplies.id
     *
     * @param id the value for supplies.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplies.name
     *
     * @return the value of supplies.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplies.name
     *
     * @param name the value for supplies.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplies.supplies_type
     *
     * @return the value of supplies.supplies_type
     *
     * @mbggenerated
     */
    public String getSuppliesType() {
        return suppliesType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplies.supplies_type
     *
     * @param suppliesType the value for supplies.supplies_type
     *
     * @mbggenerated
     */
    public void setSuppliesType(String suppliesType) {
        this.suppliesType = suppliesType == null ? null : suppliesType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplies.user_id
     *
     * @return the value of supplies.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplies.user_id
     *
     * @param userId the value for supplies.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplies.file_path
     *
     * @return the value of supplies.file_path
     *
     * @mbggenerated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplies.file_path
     *
     * @param filePath the value for supplies.file_path
     *
     * @mbggenerated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplies.info_context
     *
     * @return the value of supplies.info_context
     *
     * @mbggenerated
     */
    public String getInfoContext() {
        return infoContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplies.info_context
     *
     * @param infoContext the value for supplies.info_context
     *
     * @mbggenerated
     */
    public void setInfoContext(String infoContext) {
        this.infoContext = infoContext == null ? null : infoContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplies.stats
     *
     * @return the value of supplies.stats
     *
     * @mbggenerated
     */
    public String getStats() {
        return stats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplies.stats
     *
     * @param stats the value for supplies.stats
     *
     * @mbggenerated
     */
    public void setStats(String stats) {
        this.stats = stats == null ? null : stats.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplies.oper_fristuser
     *
     * @return the value of supplies.oper_fristuser
     *
     * @mbggenerated
     */
    public String getOperFristuser() {
        return operFristuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplies.oper_fristuser
     *
     * @param operFristuser the value for supplies.oper_fristuser
     *
     * @mbggenerated
     */
    public void setOperFristuser(String operFristuser) {
        this.operFristuser = operFristuser == null ? null : operFristuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplies.oper_fristcomment
     *
     * @return the value of supplies.oper_fristcomment
     *
     * @mbggenerated
     */
    public String getOperFristcomment() {
        return operFristcomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplies.oper_fristcomment
     *
     * @param operFristcomment the value for supplies.oper_fristcomment
     *
     * @mbggenerated
     */
    public void setOperFristcomment(String operFristcomment) {
        this.operFristcomment = operFristcomment == null ? null : operFristcomment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplies.oper_finaluser
     *
     * @return the value of supplies.oper_finaluser
     *
     * @mbggenerated
     */
    public String getOperFinaluser() {
        return operFinaluser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplies.oper_finaluser
     *
     * @param operFinaluser the value for supplies.oper_finaluser
     *
     * @mbggenerated
     */
    public void setOperFinaluser(String operFinaluser) {
        this.operFinaluser = operFinaluser == null ? null : operFinaluser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplies.oper_finalcomment
     *
     * @return the value of supplies.oper_finalcomment
     *
     * @mbggenerated
     */
    public String getOperFinalcomment() {
        return operFinalcomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplies.oper_finalcomment
     *
     * @param operFinalcomment the value for supplies.oper_finalcomment
     *
     * @mbggenerated
     */
    public void setOperFinalcomment(String operFinalcomment) {
        this.operFinalcomment = operFinalcomment == null ? null : operFinalcomment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplies.seq_number
     *
     * @return the value of supplies.seq_number
     *
     * @mbggenerated
     */
    public String getSeqNumber() {
        return seqNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplies.seq_number
     *
     * @param seqNumber the value for supplies.seq_number
     *
     * @mbggenerated
     */
    public void setSeqNumber(String seqNumber) {
        this.seqNumber = seqNumber == null ? null : seqNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplies.car_numer
     *
     * @return the value of supplies.car_numer
     *
     * @mbggenerated
     */
    public String getCarNumer() {
        return carNumer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplies.car_numer
     *
     * @param carNumer the value for supplies.car_numer
     *
     * @mbggenerated
     */
    public void setCarNumer(String carNumer) {
        this.carNumer = carNumer == null ? null : carNumer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplies.response_cid
     *
     * @return the value of supplies.response_cid
     *
     * @mbggenerated
     */
    public String getResponseCid() {
        return responseCid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplies.response_cid
     *
     * @param responseCid the value for supplies.response_cid
     *
     * @mbggenerated
     */
    public void setResponseCid(String responseCid) {
        this.responseCid = responseCid == null ? null : responseCid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplies.create_time
     *
     * @return the value of supplies.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplies.create_time
     *
     * @param createTime the value for supplies.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplies.edit_time
     *
     * @return the value of supplies.edit_time
     *
     * @mbggenerated
     */
    public Date getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplies.edit_time
     *
     * @param editTime the value for supplies.edit_time
     *
     * @mbggenerated
     */
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }
}