package com.pantuo.mybatis.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SuppliesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplies
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplies
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplies
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplies
     *
     * @mbggenerated
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplies
     *
     * @mbggenerated
     */
    protected int limitEnd = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplies
     *
     * @mbggenerated
     */
    protected String defaultVisible = "1";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplies
     *
     * @mbggenerated
     */
    protected String defaultStatusNot = "del";

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    public SuppliesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    public void setDefaultVisible(String defaultVisible) {
        this.defaultVisible=defaultVisible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    public String getDefaultVisible() {
        return defaultVisible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    public void setDefaultStatusNot(String defaultStatusNot) {
        this.defaultStatusNot=defaultStatusNot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplies
     *
     * @mbggenerated
     */
    public String getDefaultStatusNot() {
        return defaultStatusNot;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table supplies
     *
     * @mbggenerated
     */
    protected abstract class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition.startsWith("visible")) {
                SuppliesExample.this.defaultVisible = null;
            }
            if (condition.startsWith("status")) {
                SuppliesExample.this.defaultStatusNot = null;
            }
            if (condition == null) {
                return ;
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (condition.startsWith("visible")) {
                SuppliesExample.this.defaultVisible = null;
            }
            if (condition.startsWith("status")) {
                SuppliesExample.this.defaultStatusNot = null;
            }
            if (value == null) {
                return ;
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (condition.startsWith("visible")) {
                SuppliesExample.this.defaultVisible = null;
            }
            if (condition.startsWith("status")) {
                SuppliesExample.this.defaultStatusNot = null;
            }
            if (value1 == null || value2 == null) {
                return ;
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSuppliesTypeIsNull() {
            addCriterion("supplies_type is null");
            return (Criteria) this;
        }

        public Criteria andSuppliesTypeIsNotNull() {
            addCriterion("supplies_type is not null");
            return (Criteria) this;
        }

        public Criteria andSuppliesTypeEqualTo(String value) {
            addCriterion("supplies_type =", value, "suppliesType");
            return (Criteria) this;
        }

        public Criteria andSuppliesTypeNotEqualTo(String value) {
            addCriterion("supplies_type <>", value, "suppliesType");
            return (Criteria) this;
        }

        public Criteria andSuppliesTypeGreaterThan(String value) {
            addCriterion("supplies_type >", value, "suppliesType");
            return (Criteria) this;
        }

        public Criteria andSuppliesTypeGreaterThanOrEqualTo(String value) {
            addCriterion("supplies_type >=", value, "suppliesType");
            return (Criteria) this;
        }

        public Criteria andSuppliesTypeLessThan(String value) {
            addCriterion("supplies_type <", value, "suppliesType");
            return (Criteria) this;
        }

        public Criteria andSuppliesTypeLessThanOrEqualTo(String value) {
            addCriterion("supplies_type <=", value, "suppliesType");
            return (Criteria) this;
        }

        public Criteria andSuppliesTypeLike(String value) {
            addCriterion("supplies_type like", value, "suppliesType");
            return (Criteria) this;
        }

        public Criteria andSuppliesTypeNotLike(String value) {
            addCriterion("supplies_type not like", value, "suppliesType");
            return (Criteria) this;
        }

        public Criteria andSuppliesTypeIn(List<String> values) {
            addCriterion("supplies_type in", values, "suppliesType");
            return (Criteria) this;
        }

        public Criteria andSuppliesTypeNotIn(List<String> values) {
            addCriterion("supplies_type not in", values, "suppliesType");
            return (Criteria) this;
        }

        public Criteria andSuppliesTypeBetween(String value1, String value2) {
            addCriterion("supplies_type between", value1, value2, "suppliesType");
            return (Criteria) this;
        }

        public Criteria andSuppliesTypeNotBetween(String value1, String value2) {
            addCriterion("supplies_type not between", value1, value2, "suppliesType");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andFilePathIsNull() {
            addCriterion("file_path is null");
            return (Criteria) this;
        }

        public Criteria andFilePathIsNotNull() {
            addCriterion("file_path is not null");
            return (Criteria) this;
        }

        public Criteria andFilePathEqualTo(String value) {
            addCriterion("file_path =", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotEqualTo(String value) {
            addCriterion("file_path <>", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathGreaterThan(String value) {
            addCriterion("file_path >", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathGreaterThanOrEqualTo(String value) {
            addCriterion("file_path >=", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathLessThan(String value) {
            addCriterion("file_path <", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathLessThanOrEqualTo(String value) {
            addCriterion("file_path <=", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathLike(String value) {
            addCriterion("file_path like", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotLike(String value) {
            addCriterion("file_path not like", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathIn(List<String> values) {
            addCriterion("file_path in", values, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotIn(List<String> values) {
            addCriterion("file_path not in", values, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathBetween(String value1, String value2) {
            addCriterion("file_path between", value1, value2, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotBetween(String value1, String value2) {
            addCriterion("file_path not between", value1, value2, "filePath");
            return (Criteria) this;
        }

        public Criteria andInfoContextIsNull() {
            addCriterion("info_context is null");
            return (Criteria) this;
        }

        public Criteria andInfoContextIsNotNull() {
            addCriterion("info_context is not null");
            return (Criteria) this;
        }

        public Criteria andInfoContextEqualTo(String value) {
            addCriterion("info_context =", value, "infoContext");
            return (Criteria) this;
        }

        public Criteria andInfoContextNotEqualTo(String value) {
            addCriterion("info_context <>", value, "infoContext");
            return (Criteria) this;
        }

        public Criteria andInfoContextGreaterThan(String value) {
            addCriterion("info_context >", value, "infoContext");
            return (Criteria) this;
        }

        public Criteria andInfoContextGreaterThanOrEqualTo(String value) {
            addCriterion("info_context >=", value, "infoContext");
            return (Criteria) this;
        }

        public Criteria andInfoContextLessThan(String value) {
            addCriterion("info_context <", value, "infoContext");
            return (Criteria) this;
        }

        public Criteria andInfoContextLessThanOrEqualTo(String value) {
            addCriterion("info_context <=", value, "infoContext");
            return (Criteria) this;
        }

        public Criteria andInfoContextLike(String value) {
            addCriterion("info_context like", value, "infoContext");
            return (Criteria) this;
        }

        public Criteria andInfoContextNotLike(String value) {
            addCriterion("info_context not like", value, "infoContext");
            return (Criteria) this;
        }

        public Criteria andInfoContextIn(List<String> values) {
            addCriterion("info_context in", values, "infoContext");
            return (Criteria) this;
        }

        public Criteria andInfoContextNotIn(List<String> values) {
            addCriterion("info_context not in", values, "infoContext");
            return (Criteria) this;
        }

        public Criteria andInfoContextBetween(String value1, String value2) {
            addCriterion("info_context between", value1, value2, "infoContext");
            return (Criteria) this;
        }

        public Criteria andInfoContextNotBetween(String value1, String value2) {
            addCriterion("info_context not between", value1, value2, "infoContext");
            return (Criteria) this;
        }

        public Criteria andStatsIsNull() {
            addCriterion("stats is null");
            return (Criteria) this;
        }

        public Criteria andStatsIsNotNull() {
            addCriterion("stats is not null");
            return (Criteria) this;
        }

        public Criteria andStatsEqualTo(String value) {
            addCriterion("stats =", value, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsNotEqualTo(String value) {
            addCriterion("stats <>", value, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsGreaterThan(String value) {
            addCriterion("stats >", value, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsGreaterThanOrEqualTo(String value) {
            addCriterion("stats >=", value, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsLessThan(String value) {
            addCriterion("stats <", value, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsLessThanOrEqualTo(String value) {
            addCriterion("stats <=", value, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsLike(String value) {
            addCriterion("stats like", value, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsNotLike(String value) {
            addCriterion("stats not like", value, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsIn(List<String> values) {
            addCriterion("stats in", values, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsNotIn(List<String> values) {
            addCriterion("stats not in", values, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsBetween(String value1, String value2) {
            addCriterion("stats between", value1, value2, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsNotBetween(String value1, String value2) {
            addCriterion("stats not between", value1, value2, "stats");
            return (Criteria) this;
        }

        public Criteria andOperFristuserIsNull() {
            addCriterion("oper_fristuser is null");
            return (Criteria) this;
        }

        public Criteria andOperFristuserIsNotNull() {
            addCriterion("oper_fristuser is not null");
            return (Criteria) this;
        }

        public Criteria andOperFristuserEqualTo(String value) {
            addCriterion("oper_fristuser =", value, "operFristuser");
            return (Criteria) this;
        }

        public Criteria andOperFristuserNotEqualTo(String value) {
            addCriterion("oper_fristuser <>", value, "operFristuser");
            return (Criteria) this;
        }

        public Criteria andOperFristuserGreaterThan(String value) {
            addCriterion("oper_fristuser >", value, "operFristuser");
            return (Criteria) this;
        }

        public Criteria andOperFristuserGreaterThanOrEqualTo(String value) {
            addCriterion("oper_fristuser >=", value, "operFristuser");
            return (Criteria) this;
        }

        public Criteria andOperFristuserLessThan(String value) {
            addCriterion("oper_fristuser <", value, "operFristuser");
            return (Criteria) this;
        }

        public Criteria andOperFristuserLessThanOrEqualTo(String value) {
            addCriterion("oper_fristuser <=", value, "operFristuser");
            return (Criteria) this;
        }

        public Criteria andOperFristuserLike(String value) {
            addCriterion("oper_fristuser like", value, "operFristuser");
            return (Criteria) this;
        }

        public Criteria andOperFristuserNotLike(String value) {
            addCriterion("oper_fristuser not like", value, "operFristuser");
            return (Criteria) this;
        }

        public Criteria andOperFristuserIn(List<String> values) {
            addCriterion("oper_fristuser in", values, "operFristuser");
            return (Criteria) this;
        }

        public Criteria andOperFristuserNotIn(List<String> values) {
            addCriterion("oper_fristuser not in", values, "operFristuser");
            return (Criteria) this;
        }

        public Criteria andOperFristuserBetween(String value1, String value2) {
            addCriterion("oper_fristuser between", value1, value2, "operFristuser");
            return (Criteria) this;
        }

        public Criteria andOperFristuserNotBetween(String value1, String value2) {
            addCriterion("oper_fristuser not between", value1, value2, "operFristuser");
            return (Criteria) this;
        }

        public Criteria andOperFristcommentIsNull() {
            addCriterion("oper_fristcomment is null");
            return (Criteria) this;
        }

        public Criteria andOperFristcommentIsNotNull() {
            addCriterion("oper_fristcomment is not null");
            return (Criteria) this;
        }

        public Criteria andOperFristcommentEqualTo(String value) {
            addCriterion("oper_fristcomment =", value, "operFristcomment");
            return (Criteria) this;
        }

        public Criteria andOperFristcommentNotEqualTo(String value) {
            addCriterion("oper_fristcomment <>", value, "operFristcomment");
            return (Criteria) this;
        }

        public Criteria andOperFristcommentGreaterThan(String value) {
            addCriterion("oper_fristcomment >", value, "operFristcomment");
            return (Criteria) this;
        }

        public Criteria andOperFristcommentGreaterThanOrEqualTo(String value) {
            addCriterion("oper_fristcomment >=", value, "operFristcomment");
            return (Criteria) this;
        }

        public Criteria andOperFristcommentLessThan(String value) {
            addCriterion("oper_fristcomment <", value, "operFristcomment");
            return (Criteria) this;
        }

        public Criteria andOperFristcommentLessThanOrEqualTo(String value) {
            addCriterion("oper_fristcomment <=", value, "operFristcomment");
            return (Criteria) this;
        }

        public Criteria andOperFristcommentLike(String value) {
            addCriterion("oper_fristcomment like", value, "operFristcomment");
            return (Criteria) this;
        }

        public Criteria andOperFristcommentNotLike(String value) {
            addCriterion("oper_fristcomment not like", value, "operFristcomment");
            return (Criteria) this;
        }

        public Criteria andOperFristcommentIn(List<String> values) {
            addCriterion("oper_fristcomment in", values, "operFristcomment");
            return (Criteria) this;
        }

        public Criteria andOperFristcommentNotIn(List<String> values) {
            addCriterion("oper_fristcomment not in", values, "operFristcomment");
            return (Criteria) this;
        }

        public Criteria andOperFristcommentBetween(String value1, String value2) {
            addCriterion("oper_fristcomment between", value1, value2, "operFristcomment");
            return (Criteria) this;
        }

        public Criteria andOperFristcommentNotBetween(String value1, String value2) {
            addCriterion("oper_fristcomment not between", value1, value2, "operFristcomment");
            return (Criteria) this;
        }

        public Criteria andOperFinaluserIsNull() {
            addCriterion("oper_finaluser is null");
            return (Criteria) this;
        }

        public Criteria andOperFinaluserIsNotNull() {
            addCriterion("oper_finaluser is not null");
            return (Criteria) this;
        }

        public Criteria andOperFinaluserEqualTo(String value) {
            addCriterion("oper_finaluser =", value, "operFinaluser");
            return (Criteria) this;
        }

        public Criteria andOperFinaluserNotEqualTo(String value) {
            addCriterion("oper_finaluser <>", value, "operFinaluser");
            return (Criteria) this;
        }

        public Criteria andOperFinaluserGreaterThan(String value) {
            addCriterion("oper_finaluser >", value, "operFinaluser");
            return (Criteria) this;
        }

        public Criteria andOperFinaluserGreaterThanOrEqualTo(String value) {
            addCriterion("oper_finaluser >=", value, "operFinaluser");
            return (Criteria) this;
        }

        public Criteria andOperFinaluserLessThan(String value) {
            addCriterion("oper_finaluser <", value, "operFinaluser");
            return (Criteria) this;
        }

        public Criteria andOperFinaluserLessThanOrEqualTo(String value) {
            addCriterion("oper_finaluser <=", value, "operFinaluser");
            return (Criteria) this;
        }

        public Criteria andOperFinaluserLike(String value) {
            addCriterion("oper_finaluser like", value, "operFinaluser");
            return (Criteria) this;
        }

        public Criteria andOperFinaluserNotLike(String value) {
            addCriterion("oper_finaluser not like", value, "operFinaluser");
            return (Criteria) this;
        }

        public Criteria andOperFinaluserIn(List<String> values) {
            addCriterion("oper_finaluser in", values, "operFinaluser");
            return (Criteria) this;
        }

        public Criteria andOperFinaluserNotIn(List<String> values) {
            addCriterion("oper_finaluser not in", values, "operFinaluser");
            return (Criteria) this;
        }

        public Criteria andOperFinaluserBetween(String value1, String value2) {
            addCriterion("oper_finaluser between", value1, value2, "operFinaluser");
            return (Criteria) this;
        }

        public Criteria andOperFinaluserNotBetween(String value1, String value2) {
            addCriterion("oper_finaluser not between", value1, value2, "operFinaluser");
            return (Criteria) this;
        }

        public Criteria andOperFinalcommentIsNull() {
            addCriterion("oper_finalcomment is null");
            return (Criteria) this;
        }

        public Criteria andOperFinalcommentIsNotNull() {
            addCriterion("oper_finalcomment is not null");
            return (Criteria) this;
        }

        public Criteria andOperFinalcommentEqualTo(String value) {
            addCriterion("oper_finalcomment =", value, "operFinalcomment");
            return (Criteria) this;
        }

        public Criteria andOperFinalcommentNotEqualTo(String value) {
            addCriterion("oper_finalcomment <>", value, "operFinalcomment");
            return (Criteria) this;
        }

        public Criteria andOperFinalcommentGreaterThan(String value) {
            addCriterion("oper_finalcomment >", value, "operFinalcomment");
            return (Criteria) this;
        }

        public Criteria andOperFinalcommentGreaterThanOrEqualTo(String value) {
            addCriterion("oper_finalcomment >=", value, "operFinalcomment");
            return (Criteria) this;
        }

        public Criteria andOperFinalcommentLessThan(String value) {
            addCriterion("oper_finalcomment <", value, "operFinalcomment");
            return (Criteria) this;
        }

        public Criteria andOperFinalcommentLessThanOrEqualTo(String value) {
            addCriterion("oper_finalcomment <=", value, "operFinalcomment");
            return (Criteria) this;
        }

        public Criteria andOperFinalcommentLike(String value) {
            addCriterion("oper_finalcomment like", value, "operFinalcomment");
            return (Criteria) this;
        }

        public Criteria andOperFinalcommentNotLike(String value) {
            addCriterion("oper_finalcomment not like", value, "operFinalcomment");
            return (Criteria) this;
        }

        public Criteria andOperFinalcommentIn(List<String> values) {
            addCriterion("oper_finalcomment in", values, "operFinalcomment");
            return (Criteria) this;
        }

        public Criteria andOperFinalcommentNotIn(List<String> values) {
            addCriterion("oper_finalcomment not in", values, "operFinalcomment");
            return (Criteria) this;
        }

        public Criteria andOperFinalcommentBetween(String value1, String value2) {
            addCriterion("oper_finalcomment between", value1, value2, "operFinalcomment");
            return (Criteria) this;
        }

        public Criteria andOperFinalcommentNotBetween(String value1, String value2) {
            addCriterion("oper_finalcomment not between", value1, value2, "operFinalcomment");
            return (Criteria) this;
        }

        public Criteria andSeqNumberIsNull() {
            addCriterion("seq_number is null");
            return (Criteria) this;
        }

        public Criteria andSeqNumberIsNotNull() {
            addCriterion("seq_number is not null");
            return (Criteria) this;
        }

        public Criteria andSeqNumberEqualTo(String value) {
            addCriterion("seq_number =", value, "seqNumber");
            return (Criteria) this;
        }

        public Criteria andSeqNumberNotEqualTo(String value) {
            addCriterion("seq_number <>", value, "seqNumber");
            return (Criteria) this;
        }

        public Criteria andSeqNumberGreaterThan(String value) {
            addCriterion("seq_number >", value, "seqNumber");
            return (Criteria) this;
        }

        public Criteria andSeqNumberGreaterThanOrEqualTo(String value) {
            addCriterion("seq_number >=", value, "seqNumber");
            return (Criteria) this;
        }

        public Criteria andSeqNumberLessThan(String value) {
            addCriterion("seq_number <", value, "seqNumber");
            return (Criteria) this;
        }

        public Criteria andSeqNumberLessThanOrEqualTo(String value) {
            addCriterion("seq_number <=", value, "seqNumber");
            return (Criteria) this;
        }

        public Criteria andSeqNumberLike(String value) {
            addCriterion("seq_number like", value, "seqNumber");
            return (Criteria) this;
        }

        public Criteria andSeqNumberNotLike(String value) {
            addCriterion("seq_number not like", value, "seqNumber");
            return (Criteria) this;
        }

        public Criteria andSeqNumberIn(List<String> values) {
            addCriterion("seq_number in", values, "seqNumber");
            return (Criteria) this;
        }

        public Criteria andSeqNumberNotIn(List<String> values) {
            addCriterion("seq_number not in", values, "seqNumber");
            return (Criteria) this;
        }

        public Criteria andSeqNumberBetween(String value1, String value2) {
            addCriterion("seq_number between", value1, value2, "seqNumber");
            return (Criteria) this;
        }

        public Criteria andSeqNumberNotBetween(String value1, String value2) {
            addCriterion("seq_number not between", value1, value2, "seqNumber");
            return (Criteria) this;
        }

        public Criteria andCarNumerIsNull() {
            addCriterion("car_numer is null");
            return (Criteria) this;
        }

        public Criteria andCarNumerIsNotNull() {
            addCriterion("car_numer is not null");
            return (Criteria) this;
        }

        public Criteria andCarNumerEqualTo(String value) {
            addCriterion("car_numer =", value, "carNumer");
            return (Criteria) this;
        }

        public Criteria andCarNumerNotEqualTo(String value) {
            addCriterion("car_numer <>", value, "carNumer");
            return (Criteria) this;
        }

        public Criteria andCarNumerGreaterThan(String value) {
            addCriterion("car_numer >", value, "carNumer");
            return (Criteria) this;
        }

        public Criteria andCarNumerGreaterThanOrEqualTo(String value) {
            addCriterion("car_numer >=", value, "carNumer");
            return (Criteria) this;
        }

        public Criteria andCarNumerLessThan(String value) {
            addCriterion("car_numer <", value, "carNumer");
            return (Criteria) this;
        }

        public Criteria andCarNumerLessThanOrEqualTo(String value) {
            addCriterion("car_numer <=", value, "carNumer");
            return (Criteria) this;
        }

        public Criteria andCarNumerLike(String value) {
            addCriterion("car_numer like", value, "carNumer");
            return (Criteria) this;
        }

        public Criteria andCarNumerNotLike(String value) {
            addCriterion("car_numer not like", value, "carNumer");
            return (Criteria) this;
        }

        public Criteria andCarNumerIn(List<String> values) {
            addCriterion("car_numer in", values, "carNumer");
            return (Criteria) this;
        }

        public Criteria andCarNumerNotIn(List<String> values) {
            addCriterion("car_numer not in", values, "carNumer");
            return (Criteria) this;
        }

        public Criteria andCarNumerBetween(String value1, String value2) {
            addCriterion("car_numer between", value1, value2, "carNumer");
            return (Criteria) this;
        }

        public Criteria andCarNumerNotBetween(String value1, String value2) {
            addCriterion("car_numer not between", value1, value2, "carNumer");
            return (Criteria) this;
        }

        public Criteria andResponseCidIsNull() {
            addCriterion("response_cid is null");
            return (Criteria) this;
        }

        public Criteria andResponseCidIsNotNull() {
            addCriterion("response_cid is not null");
            return (Criteria) this;
        }

        public Criteria andResponseCidEqualTo(String value) {
            addCriterion("response_cid =", value, "responseCid");
            return (Criteria) this;
        }

        public Criteria andResponseCidNotEqualTo(String value) {
            addCriterion("response_cid <>", value, "responseCid");
            return (Criteria) this;
        }

        public Criteria andResponseCidGreaterThan(String value) {
            addCriterion("response_cid >", value, "responseCid");
            return (Criteria) this;
        }

        public Criteria andResponseCidGreaterThanOrEqualTo(String value) {
            addCriterion("response_cid >=", value, "responseCid");
            return (Criteria) this;
        }

        public Criteria andResponseCidLessThan(String value) {
            addCriterion("response_cid <", value, "responseCid");
            return (Criteria) this;
        }

        public Criteria andResponseCidLessThanOrEqualTo(String value) {
            addCriterion("response_cid <=", value, "responseCid");
            return (Criteria) this;
        }

        public Criteria andResponseCidLike(String value) {
            addCriterion("response_cid like", value, "responseCid");
            return (Criteria) this;
        }

        public Criteria andResponseCidNotLike(String value) {
            addCriterion("response_cid not like", value, "responseCid");
            return (Criteria) this;
        }

        public Criteria andResponseCidIn(List<String> values) {
            addCriterion("response_cid in", values, "responseCid");
            return (Criteria) this;
        }

        public Criteria andResponseCidNotIn(List<String> values) {
            addCriterion("response_cid not in", values, "responseCid");
            return (Criteria) this;
        }

        public Criteria andResponseCidBetween(String value1, String value2) {
            addCriterion("response_cid between", value1, value2, "responseCid");
            return (Criteria) this;
        }

        public Criteria andResponseCidNotBetween(String value1, String value2) {
            addCriterion("response_cid not between", value1, value2, "responseCid");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeIsNull() {
            addCriterion("edit_time is null");
            return (Criteria) this;
        }

        public Criteria andEditTimeIsNotNull() {
            addCriterion("edit_time is not null");
            return (Criteria) this;
        }

        public Criteria andEditTimeEqualTo(Date value) {
            addCriterion("edit_time =", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeNotEqualTo(Date value) {
            addCriterion("edit_time <>", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeGreaterThan(Date value) {
            addCriterion("edit_time >", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("edit_time >=", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeLessThan(Date value) {
            addCriterion("edit_time <", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeLessThanOrEqualTo(Date value) {
            addCriterion("edit_time <=", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeIn(List<Date> values) {
            addCriterion("edit_time in", values, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeNotIn(List<Date> values) {
            addCriterion("edit_time not in", values, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeBetween(Date value1, Date value2) {
            addCriterion("edit_time between", value1, value2, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeNotBetween(Date value1, Date value2) {
            addCriterion("edit_time not between", value1, value2, "editTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table supplies
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table supplies
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}