package com.pantuo.mybatis.domain;

import java.io.Serializable;
import java.util.Date;

public class SuppliesHistory implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplies_history.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplies_history.supplies_id
     *
     * @mbggenerated
     */
    private Integer suppliesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplies_history.stats
     *
     * @mbggenerated
     */
    private String stats;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplies_history.oper_user
     *
     * @mbggenerated
     */
    private String operUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplies_history.oper_comment
     *
     * @mbggenerated
     */
    private String operComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplies_history.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplies_history
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplies_history.id
     *
     * @return the value of supplies_history.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplies_history.id
     *
     * @param id the value for supplies_history.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplies_history.supplies_id
     *
     * @return the value of supplies_history.supplies_id
     *
     * @mbggenerated
     */
    public Integer getSuppliesId() {
        return suppliesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplies_history.supplies_id
     *
     * @param suppliesId the value for supplies_history.supplies_id
     *
     * @mbggenerated
     */
    public void setSuppliesId(Integer suppliesId) {
        this.suppliesId = suppliesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplies_history.stats
     *
     * @return the value of supplies_history.stats
     *
     * @mbggenerated
     */
    public String getStats() {
        return stats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplies_history.stats
     *
     * @param stats the value for supplies_history.stats
     *
     * @mbggenerated
     */
    public void setStats(String stats) {
        this.stats = stats == null ? null : stats.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplies_history.oper_user
     *
     * @return the value of supplies_history.oper_user
     *
     * @mbggenerated
     */
    public String getOperUser() {
        return operUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplies_history.oper_user
     *
     * @param operUser the value for supplies_history.oper_user
     *
     * @mbggenerated
     */
    public void setOperUser(String operUser) {
        this.operUser = operUser == null ? null : operUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplies_history.oper_comment
     *
     * @return the value of supplies_history.oper_comment
     *
     * @mbggenerated
     */
    public String getOperComment() {
        return operComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplies_history.oper_comment
     *
     * @param operComment the value for supplies_history.oper_comment
     *
     * @mbggenerated
     */
    public void setOperComment(String operComment) {
        this.operComment = operComment == null ? null : operComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplies_history.create_time
     *
     * @return the value of supplies_history.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplies_history.create_time
     *
     * @param createTime the value for supplies_history.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}