package com.pantuo.mybatis.domain;

import java.io.Serializable;

public class SysConfig implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.bl
     *
     * @mbggenerated
     */
    private Integer bl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.key_desc
     *
     * @mbggenerated
     */
    private String keyDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.key_code
     *
     * @mbggenerated
     */
    private String keyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_config
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.id
     *
     * @return the value of sys_config.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.id
     *
     * @param id the value for sys_config.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.bl
     *
     * @return the value of sys_config.bl
     *
     * @mbggenerated
     */
    public Integer getBl() {
        return bl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.bl
     *
     * @param bl the value for sys_config.bl
     *
     * @mbggenerated
     */
    public void setBl(Integer bl) {
        this.bl = bl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.key_desc
     *
     * @return the value of sys_config.key_desc
     *
     * @mbggenerated
     */
    public String getKeyDesc() {
        return keyDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.key_desc
     *
     * @param keyDesc the value for sys_config.key_desc
     *
     * @mbggenerated
     */
    public void setKeyDesc(String keyDesc) {
        this.keyDesc = keyDesc == null ? null : keyDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.key_code
     *
     * @return the value of sys_config.key_code
     *
     * @mbggenerated
     */
    public String getKeyCode() {
        return keyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.key_code
     *
     * @param keyCode the value for sys_config.key_code
     *
     * @mbggenerated
     */
    public void setKeyCode(String keyCode) {
        this.keyCode = keyCode == null ? null : keyCode.trim();
    }
}