package com.pantuo.web.view;

import java.io.Serializable;
import java.util.Date;

public class Offlinecontract implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.updated
     *
     * @mbggenerated
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.city
     *
     * @mbggenerated
     */
    private Integer city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.adcontent
     *
     * @mbggenerated
     */
    private String adcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.adway
     *
     * @mbggenerated
     */
    private String adway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.amounts
     *
     * @mbggenerated
     */
    private String amounts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.company
     *
     * @mbggenerated
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.company_addr
     *
     * @mbggenerated
     */
    private String companyAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.contract_code
     *
     * @mbggenerated
     */
    private String contractCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.contract_name
     *
     * @mbggenerated
     */
    private String contractName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.days
     *
     * @mbggenerated
     */
    private Integer days;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.is_del
     *
     * @mbggenerated
     */
    private Boolean isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.is_schedule
     *
     * @mbggenerated
     */
    private Boolean isSchedule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.legalman
     *
     * @mbggenerated
     */
    private String legalman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.linecontent
     *
     * @mbggenerated
     */
    private String linecontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.markcenter
     *
     * @mbggenerated
     */
    private String markcenter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.otype
     *
     * @mbggenerated
     */
    private Integer otype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.pay_date
     *
     * @mbggenerated
     */
    private Date payDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.payway
     *
     * @mbggenerated
     */
    private String payway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.phone_num
     *
     * @mbggenerated
     */
    private String phoneNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.relate_man
     *
     * @mbggenerated
     */
    private String relateMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.salesman
     *
     * @mbggenerated
     */
    private String salesman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.seria_num
     *
     * @mbggenerated
     */
    private Long seriaNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.sign_date
     *
     * @mbggenerated
     */
    private Date signDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offlinecontract.total_num
     *
     * @mbggenerated
     */
    private Integer totalNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table offlinecontract
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.id
     *
     * @return the value of offlinecontract.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.id
     *
     * @param id the value for offlinecontract.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.created
     *
     * @return the value of offlinecontract.created
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.created
     *
     * @param created the value for offlinecontract.created
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.updated
     *
     * @return the value of offlinecontract.updated
     *
     * @mbggenerated
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.updated
     *
     * @param updated the value for offlinecontract.updated
     *
     * @mbggenerated
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.city
     *
     * @return the value of offlinecontract.city
     *
     * @mbggenerated
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.city
     *
     * @param city the value for offlinecontract.city
     *
     * @mbggenerated
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.adcontent
     *
     * @return the value of offlinecontract.adcontent
     *
     * @mbggenerated
     */
    public String getAdcontent() {
        return adcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.adcontent
     *
     * @param adcontent the value for offlinecontract.adcontent
     *
     * @mbggenerated
     */
    public void setAdcontent(String adcontent) {
        this.adcontent = adcontent == null ? null : adcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.adway
     *
     * @return the value of offlinecontract.adway
     *
     * @mbggenerated
     */
    public String getAdway() {
        return adway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.adway
     *
     * @param adway the value for offlinecontract.adway
     *
     * @mbggenerated
     */
    public void setAdway(String adway) {
        this.adway = adway == null ? null : adway.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.amounts
     *
     * @return the value of offlinecontract.amounts
     *
     * @mbggenerated
     */
    public String getAmounts() {
        return amounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.amounts
     *
     * @param amounts the value for offlinecontract.amounts
     *
     * @mbggenerated
     */
    public void setAmounts(String amounts) {
        this.amounts = amounts == null ? null : amounts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.company
     *
     * @return the value of offlinecontract.company
     *
     * @mbggenerated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.company
     *
     * @param company the value for offlinecontract.company
     *
     * @mbggenerated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.company_addr
     *
     * @return the value of offlinecontract.company_addr
     *
     * @mbggenerated
     */
    public String getCompanyAddr() {
        return companyAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.company_addr
     *
     * @param companyAddr the value for offlinecontract.company_addr
     *
     * @mbggenerated
     */
    public void setCompanyAddr(String companyAddr) {
        this.companyAddr = companyAddr == null ? null : companyAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.contract_code
     *
     * @return the value of offlinecontract.contract_code
     *
     * @mbggenerated
     */
    public String getContractCode() {
        return contractCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.contract_code
     *
     * @param contractCode the value for offlinecontract.contract_code
     *
     * @mbggenerated
     */
    public void setContractCode(String contractCode) {
        this.contractCode = contractCode == null ? null : contractCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.contract_name
     *
     * @return the value of offlinecontract.contract_name
     *
     * @mbggenerated
     */
    public String getContractName() {
        return contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.contract_name
     *
     * @param contractName the value for offlinecontract.contract_name
     *
     * @mbggenerated
     */
    public void setContractName(String contractName) {
        this.contractName = contractName == null ? null : contractName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.creator
     *
     * @return the value of offlinecontract.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.creator
     *
     * @param creator the value for offlinecontract.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.days
     *
     * @return the value of offlinecontract.days
     *
     * @mbggenerated
     */
    public Integer getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.days
     *
     * @param days the value for offlinecontract.days
     *
     * @mbggenerated
     */
    public void setDays(Integer days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.is_del
     *
     * @return the value of offlinecontract.is_del
     *
     * @mbggenerated
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.is_del
     *
     * @param isDel the value for offlinecontract.is_del
     *
     * @mbggenerated
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.is_schedule
     *
     * @return the value of offlinecontract.is_schedule
     *
     * @mbggenerated
     */
    public Boolean getIsSchedule() {
        return isSchedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.is_schedule
     *
     * @param isSchedule the value for offlinecontract.is_schedule
     *
     * @mbggenerated
     */
    public void setIsSchedule(Boolean isSchedule) {
        this.isSchedule = isSchedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.legalman
     *
     * @return the value of offlinecontract.legalman
     *
     * @mbggenerated
     */
    public String getLegalman() {
        return legalman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.legalman
     *
     * @param legalman the value for offlinecontract.legalman
     *
     * @mbggenerated
     */
    public void setLegalman(String legalman) {
        this.legalman = legalman == null ? null : legalman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.linecontent
     *
     * @return the value of offlinecontract.linecontent
     *
     * @mbggenerated
     */
    public String getLinecontent() {
        return linecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.linecontent
     *
     * @param linecontent the value for offlinecontract.linecontent
     *
     * @mbggenerated
     */
    public void setLinecontent(String linecontent) {
        this.linecontent = linecontent == null ? null : linecontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.markcenter
     *
     * @return the value of offlinecontract.markcenter
     *
     * @mbggenerated
     */
    public String getMarkcenter() {
        return markcenter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.markcenter
     *
     * @param markcenter the value for offlinecontract.markcenter
     *
     * @mbggenerated
     */
    public void setMarkcenter(String markcenter) {
        this.markcenter = markcenter == null ? null : markcenter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.otype
     *
     * @return the value of offlinecontract.otype
     *
     * @mbggenerated
     */
    public Integer getOtype() {
        return otype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.otype
     *
     * @param otype the value for offlinecontract.otype
     *
     * @mbggenerated
     */
    public void setOtype(Integer otype) {
        this.otype = otype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.pay_date
     *
     * @return the value of offlinecontract.pay_date
     *
     * @mbggenerated
     */
    public Date getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.pay_date
     *
     * @param payDate the value for offlinecontract.pay_date
     *
     * @mbggenerated
     */
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.payway
     *
     * @return the value of offlinecontract.payway
     *
     * @mbggenerated
     */
    public String getPayway() {
        return payway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.payway
     *
     * @param payway the value for offlinecontract.payway
     *
     * @mbggenerated
     */
    public void setPayway(String payway) {
        this.payway = payway == null ? null : payway.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.phone_num
     *
     * @return the value of offlinecontract.phone_num
     *
     * @mbggenerated
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.phone_num
     *
     * @param phoneNum the value for offlinecontract.phone_num
     *
     * @mbggenerated
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum == null ? null : phoneNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.relate_man
     *
     * @return the value of offlinecontract.relate_man
     *
     * @mbggenerated
     */
    public String getRelateMan() {
        return relateMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.relate_man
     *
     * @param relateMan the value for offlinecontract.relate_man
     *
     * @mbggenerated
     */
    public void setRelateMan(String relateMan) {
        this.relateMan = relateMan == null ? null : relateMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.remarks
     *
     * @return the value of offlinecontract.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.remarks
     *
     * @param remarks the value for offlinecontract.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.salesman
     *
     * @return the value of offlinecontract.salesman
     *
     * @mbggenerated
     */
    public String getSalesman() {
        return salesman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.salesman
     *
     * @param salesman the value for offlinecontract.salesman
     *
     * @mbggenerated
     */
    public void setSalesman(String salesman) {
        this.salesman = salesman == null ? null : salesman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.seria_num
     *
     * @return the value of offlinecontract.seria_num
     *
     * @mbggenerated
     */
    public Long getSeriaNum() {
        return seriaNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.seria_num
     *
     * @param seriaNum the value for offlinecontract.seria_num
     *
     * @mbggenerated
     */
    public void setSeriaNum(Long seriaNum) {
        this.seriaNum = seriaNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.sign_date
     *
     * @return the value of offlinecontract.sign_date
     *
     * @mbggenerated
     */
    public Date getSignDate() {
        return signDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.sign_date
     *
     * @param signDate the value for offlinecontract.sign_date
     *
     * @mbggenerated
     */
    public void setSignDate(Date signDate) {
        this.signDate = signDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offlinecontract.total_num
     *
     * @return the value of offlinecontract.total_num
     *
     * @mbggenerated
     */
    public Integer getTotalNum() {
        return totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offlinecontract.total_num
     *
     * @param totalNum the value for offlinecontract.total_num
     *
     * @mbggenerated
     */
    public void setTotalNum(Integer totalNum) {
        this.totalNum = totalNum;
    }
}